#cloud-config
write_files:
  - path: /home/${UserName}/.ssh/${File1Name}
    encoding: base64
    content: ${base64encode(File1Content)}
    owner: '${UserName}:${UserName}'
    permissions: '0400'
    defer: true
  - path: /home/${UserName}/.ssh/${File2Name}
    encoding: base64
    content: ${base64encode(File2Content)}
    owner: '${UserName}:${UserName}'
    permissions: '0644'
    defer: true
  - path: /home/${UserName}/.ssh/${File3Name}
    encoding: base64
    content: ${base64encode(File3Content)}
    owner: '${UserName}:${UserName}'
    permissions: '0644'
    defer: true
runcmd:
  - chmod 755 /home/${UserName}/.ssh
  - chown ${UserName}:${UserName} /home/${UserName}/.ssh